name: Ansible

on:
  workflow_dispatch:

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Ansible
        run: pip install ansible-core

      - name: Show Ansible version
        run: ansible --version
